version: '3.8'

services:
  ollama:
    image: docker.io/ollama/ollama
    container_name: ollama-llm-capability
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 6g
          cpus: '4'
        reservations:
          memory: 4g
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - OLLAMA_NUM_PARALLEL=4

volumes:
  ollama-data:
    driver: local
