services:
  ollama:
    image: docker.io/ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 6g
    restart: unless-stopped

volumes:
  ollama-data:
